
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 96
#define YY_END_OF_BUFFER 97
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[260] =
    {   0,
        0,    0,   97,   95,   94,   94,   81,   95,   93,   87,
       80,   95,   75,   76,   85,   84,   72,   83,   79,   86,
       38,   38,   73,   69,   88,   74,   89,   92,   37,   37,
       77,   78,   90,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   70,   91,
       71,   82,   68,    0,   46,    0,   54,   71,   63,   55,
        0,    0,   52,   60,   50,   61,   51,   62,    0,   44,
        0,    2,   53,   45,   38,    0,   41,    0,   38,   78,
       70,   77,   59,   65,   67,   66,   58,    0,   37,   37,
        0,    0,   56,   37,   37,   37,   37,   37,   37,   10,

       37,   37,   37,   37,   37,   11,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,   37,   57,   64,   42,
       47,    0,   44,    0,    0,    2,   44,    0,   45,   40,
        0,   43,   39,   49,   48,   36,   37,   37,   37,   37,
       37,   37,   37,   37,   37,   37,    8,   37,   37,    5,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   37,   37,   37,    0,   44,    0,    1,    0,
       44,    0,   45,   43,   39,   14,   37,   16,    6,   37,
       37,   37,   37,   37,   21,   37,   37,   24,   37,   25,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   37,

       37,    7,   37,   37,    0,    0,    0,   44,   15,   17,
       37,   37,   37,   37,   37,   23,   37,   37,   37,   27,
       37,   37,   37,   37,   37,   37,   33,   37,   37,    9,
        1,   37,   37,    3,   20,   22,   37,   37,   13,   28,
       29,   30,   31,   12,   37,   37,   37,   37,   19,    4,
       37,   32,   37,   37,   18,   26,   34,   35,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   29,
       29,   29,   29,   29,   31,   29,   29,   32,   29,   29,
       33,   34,   35,   36,   29,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   29,   46,   47,   48,   49,
       50,   51,   29,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   61,   62,   63,   64,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        6,    6,    1,    1,    1,    1,    5,    5,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[268] =
    {   0,
        0,    0,  231, 1040, 1040, 1040,  207,   60, 1040,   43,
       60,  185, 1040, 1040,  186,   56, 1040,   57,   55,   65,
       79,   74,  178, 1040,   80,  177,   52, 1040,   98,  114,
     1040, 1040,  162,  106,  120,  125,  129,  133,  137,  147,
      141,  155,  162,  170,  176,  180,  188,  192, 1040,   66,
     1040, 1040, 1040,   65, 1040,  165, 1040, 1040, 1040, 1040,
      133,   75, 1040, 1040, 1040, 1040, 1040, 1040,  142,  198,
      142,    0, 1040,  214,  232,  234,  146,    0,  250, 1040,
     1040, 1040,  127, 1040, 1040, 1040,  123,   96,    0,  202,
      130,   97, 1040,  256,  266,  270,  274,  280,  284,  290,

      296,  300,  306,  312,  316,  320,  324,  328,  339,  334,
      343,  350,  355,  372,  376,  380,  388, 1040, 1040, 1040,
     1040,  252, 1040,  115,   74,    0,  390,  397, 1040,  350,
       89,  416,  383, 1040, 1040, 1040,  423,  429,  433,  437,
      441,  446,  452,  459,  463,  468,  480,  484,  490,  494,
      498,  502,  506,  510,  514,  524,  520,  530,  534,  538,
      548,  552,  559,  564,  568,   94,  572,  266, 1040,  590,
     1040,  194,  576, 1040,  580,  606,  610,  614,  618,  622,
      626,  630,  634,  639,  643,  647,  651,  656,  661,  671,
      675,  679,  684,  688,  692,  696,  701,  705,  714,  718,

      727,  731,  737,  741,  106,  348,  204,  733,  746,  750,
      755,  760,  765,  769,  774,  778,  782,  793,  797,  801,
      808,  812,  816,  820,  824,  834,  840,  844,  851,  860,
       84,  864,  868,  872,  876,  881,  885,  889,  893,  897,
      902,  909,  913,  917,  921,  925,  929,  933,  937,  941,
      946,  951,  959,  963,  967,  971,  975,  984, 1040, 1004,
     1010, 1013, 1019, 1025,   80, 1027, 1033
    } ;

static const flex_int16_t yy_def[268] =
    {   0,
      259,    1,  259,  259,  259,  259,  259,  260,  259,  259,
      259,  261,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  262,  262,
      259,  259,  259,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  259,  259,
      259,  259,  259,  260,  259,  260,  259,  259,  259,  259,
      261,  261,  259,  259,  259,  259,  259,  259,  259,  259,
      263,  264,  259,  259,  259,  259,  259,  265,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  266,  262,
      260,  261,  259,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  259,  259,  259,
      259,  259,  259,  263,  263,  264,  259,  259,  259,  259,
      259,  259,  265,  259,  259,  259,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  259,  259,  267,  259,  259,
      259,  259,  259,  259,  259,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,

      262,  262,  262,  262,  263,  267,  259,  259,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      263,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,  262,  262,
      262,  262,  262,  262,  262,  262,  262,  262,    0,  259,
      259,  259,  259,  259,  259,  259,  259
    } ;

static const flex_int16_t yy_nxt[1105] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   29,   29,   29,   30,
       29,   29,   31,    4,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   29,   41,   29,   42,   29,   29,   29,
       29,   43,   44,   45,   46,   47,   48,   29,   29,   29,
       49,   50,   51,   52,   55,   57,   58,   59,   64,   55,
       69,   66,   70,   70,   86,   87,   71,  259,   65,   67,
       68,   72,   60,   61,  133,  168,   81,   73,  118,   74,
      169,   79,   79,   56,   74,  125,   75,   75,   56,   82,

       76,   83,   84,   77,   77,   76,  132,  132,   77,   77,
       78,  167,  167,   88,   76,   89,   89,  125,   91,   76,
       77,   88,   92,   89,   89,   77,  125,  119,   77,   88,
       62,   89,   89,   77,   55,   88,   78,   89,   89,  136,
       88,  120,   89,   89,   88,  135,   89,   89,   88,  134,
       89,   89,   88,  125,   89,   89,   88,  121,   89,   89,
       94,   96,   88,   56,   89,   89,   62,  259,   97,   99,
       88,   95,   89,   89,   98,   77,   77,   88,  100,   89,
       89,  101,  106,  103,   93,   88,  104,   89,   89,  107,
      102,   88,   77,   89,   89,   88,  105,   89,   89,   85,

       77,   80,  109,   88,  108,   89,   89,   88,   63,   89,
       89,  173,  173,  110,  111,   70,   70,   88,   62,   89,
       89,  208,  208,  112,  122,  123,  113,  123,  115,   53,
      259,  127,  127,  259,  114,  117,  259,  116,  122,  123,
      128,  129,  259,  129,  123,  259,  131,   74,  131,   75,
       75,  132,  132,  259,  128,  129,  259,  259,   76,  259,
      129,  130,  130,  259,  166,   74,  166,   79,   79,  167,
      167,   88,   76,   89,   89,  259,   76,  206,  130,   77,
       77,   88,  124,   89,   89,   88,  130,   89,   89,   88,
       76,   89,   89,  259,  259,   88,   77,   89,   89,   88,

      259,   89,   89,  259,   77,   88,  138,   89,   89,  137,
      140,   88,  259,   89,   89,   88,  259,   89,   89,  259,
      259,   88,  139,   89,   89,  142,  259,   88,  141,   89,
       89,   88,  259,   89,   89,   88,  259,   89,   89,   88,
      259,   89,   89,   88,  143,   89,   89,  259,  259,   88,
      144,   89,   89,  145,   88,  146,   89,   89,   88,  206,
       89,   89,  149,  147,  231,   88,  259,   89,   89,  148,
       88,  259,   89,   89,  259,  259,  151,  150,  259,  130,
      130,  152,  259,  154,  259,  155,  157,   88,  259,   89,
       89,   88,  153,   89,   89,   88,  130,   89,   89,  159,

      259,  158,  156,   88,  130,   89,   89,  127,  127,  172,
      259,  172,  175,  175,  173,  173,  170,  171,  259,  171,
      161,  259,  160,  259,  163,  259,  164,  259,  162,  175,
      170,  171,  165,  132,  132,  259,  171,  175,   88,  259,
       89,   89,  259,  174,   88,  174,   89,   89,   88,  259,
       89,   89,   88,  259,   89,   89,   88,  174,   89,   89,
      259,   88,  174,   89,   89,  177,  259,   88,  259,   89,
       89,  259,  176,  178,   88,  259,   89,   89,   88,  259,
       89,   89,  182,   88,  259,   89,   89,  259,  179,  184,
      183,  259,  259,  180,  181,   88,  259,   89,   89,   88,

      259,   89,   89,  186,  187,   88,  185,   89,   89,   88,
      259,   89,   89,   88,  259,   89,   89,   88,  259,   89,
       89,   88,  259,   89,   89,   88,  259,   89,   89,   88,
      259,   89,   89,  188,  259,   88,  189,   89,   89,   88,
      190,   89,   89,  259,  259,   88,  191,   89,   89,   88,
      259,   89,   89,   88,  259,   89,   89,  259,  259,  259,
      192,  193,  194,   88,  195,   89,   89,   88,  259,   89,
       89,  259,  259,  196,   88,  259,   89,   89,  199,   88,
      259,   89,   89,   88,  197,   89,   89,  198,  259,  167,
      167,  259,  259,  173,  173,  259,  201,  200,  202,  123,

      203,  123,  207,  129,  207,  129,  259,  208,  208,  175,
      175,  259,  259,  123,  204,  259,  259,  129,  123,  259,
      259,   88,  129,   89,   89,   88,  175,   89,   89,   88,
      259,   89,   89,   88,  175,   89,   89,   88,  259,   89,
       89,   88,  259,   89,   89,   88,  259,   89,   89,   88,
      259,   89,   89,  259,   88,  209,   89,   89,   88,  259,
       89,   89,   88,  259,   89,   89,   88,  259,   89,   89,
      211,   88,  259,   89,   89,  210,   88,  259,   89,   89,
      259,  259,  213,  259,  212,  214,   88,  259,   89,   89,
       88,  259,   89,   89,   88,  259,   89,   89,  215,   88,

      259,   89,   89,   88,  216,   89,   89,   88,  259,   89,
       89,   88,  259,   89,   89,  217,   88,  259,   89,   89,
       88,  259,   89,   89,  259,  259,  259,  218,  221,   88,
      219,   89,   89,   88,  259,   89,   89,  220,  259,  224,
      223,  222,   88,  225,   89,   89,   88,  259,   89,   89,
      208,  208,   88,  226,   89,   89,   88,  259,   89,   89,
      171,   88,  171,   89,   89,   88,  227,   89,   89,  228,
       88,  259,   89,   89,  171,   88,  259,   89,   89,  171,
       88,  230,   89,   89,   88,  259,   89,   89,  259,   88,
      229,   89,   89,   88,  259,   89,   89,   88,  259,   89,

       89,  259,  259,  232,  259,  234,  233,  259,   88,  235,
       89,   89,   88,  259,   89,   89,   88,  259,   89,   89,
      259,  237,  236,   88,  259,   89,   89,   88,  259,   89,
       89,   88,  259,   89,   89,   88,  259,   89,   89,   88,
      259,   89,   89,  259,  259,  239,  238,  240,  259,   88,
      259,   89,   89,  241,  242,   88,  259,   89,   89,   88,
      259,   89,   89,  259,  259,  259,   88,  244,   89,   89,
      259,  259,  259,  243,  245,   88,  259,   89,   89,   88,
      259,   89,   89,   88,  259,   89,   89,   88,  259,   89,
       89,   88,  246,   89,   89,  247,   88,  259,   89,   89,

       88,  259,   89,   89,   88,  259,   89,   89,   88,  259,
       89,   89,   88,  259,   89,   89,  259,   88,  248,   89,
       89,  249,  259,  259,   88,  250,   89,   89,   88,  251,
       89,   89,   88,  259,   89,   89,   88,  259,   89,   89,
       88,  259,   89,   89,   88,  259,   89,   89,   88,  259,
       89,   89,   88,  259,   89,   89,   88,  259,   89,   89,
      259,   88,  252,   89,   89,  253,   88,  259,   89,   89,
      259,  259,  259,  255,   88,  254,   89,   89,   88,  259,
       89,   89,   88,  259,   89,   89,   88,  259,   89,   89,
       88,  259,   89,   89,  259,  259,  259,  256,  257,   88,

      259,   89,   89,  258,   54,   54,   54,   54,   54,   54,
       61,   61,  259,   61,   61,   61,   90,   90,   90,  124,
      124,  124,  124,  124,  124,  126,  259,  126,  126,  126,
      126,   89,   89,  205,  205,  205,  205,  205,  205,    3,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259
    } ;

static const flex_int16_t yy_chk[1105] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   10,   10,   11,   16,   54,
       19,   18,   19,   19,   27,   27,   20,   62,   16,   18,
       18,   20,   11,   62,  265,  125,   25,   20,   50,   22,
      125,   22,   22,    8,   21,  231,   21,   21,   54,   25,

       22,   25,   25,   22,   22,   21,  131,  131,   21,   21,
       21,  166,  166,   29,   22,   29,   29,  205,   30,   21,
       22,   34,   30,   34,   34,   21,  124,   50,   22,   30,
       92,   30,   30,   21,   91,   35,   21,   35,   35,   88,
       36,   61,   36,   36,   37,   87,   37,   37,   38,   83,
       38,   38,   39,   71,   39,   39,   41,   69,   41,   41,
       34,   36,   40,   91,   40,   40,   61,   56,   36,   37,
       42,   35,   42,   42,   36,   77,   77,   43,   37,   43,
       43,   38,   41,   39,   33,   44,   39,   44,   44,   41,
       38,   45,   77,   45,   45,   46,   40,   46,   46,   26,

       77,   23,   43,   47,   42,   47,   47,   48,   15,   48,
       48,  172,  172,   44,   44,   70,   70,   90,   12,   90,
       90,  207,  207,   44,   70,   70,   44,   70,   46,    7,
        3,   74,   74,    0,   45,   48,    0,   47,   70,   70,
       74,   74,    0,   74,   70,    0,   76,   75,   76,   75,
       75,   76,   76,    0,   74,   74,    0,    0,   75,    0,
       74,   75,   75,    0,  122,   79,  122,   79,   79,  122,
      122,   94,   75,   94,   94,    0,   79,  168,   75,   79,
       79,   95,  168,   95,   95,   96,   75,   96,   96,   97,
       79,   97,   97,    0,    0,   98,   79,   98,   98,   99,

        0,   99,   99,    0,   79,  100,   95,  100,  100,   94,
       97,  101,    0,  101,  101,  102,    0,  102,  102,    0,
        0,  103,   96,  103,  103,   99,    0,  104,   98,  104,
      104,  105,    0,  105,  105,  106,    0,  106,  106,  107,
        0,  107,  107,  108,  100,  108,  108,    0,    0,  110,
      101,  110,  110,  102,  109,  103,  109,  109,  111,  206,
      111,  111,  107,  104,  206,  112,    0,  112,  112,  105,
      113,    0,  113,  113,    0,    0,  108,  107,    0,  130,
      130,  109,    0,  110,    0,  111,  112,  114,    0,  114,
      114,  115,  109,  115,  115,  116,  130,  116,  116,  113,

        0,  112,  111,  117,  130,  117,  117,  127,  127,  128,
        0,  128,  133,  133,  128,  128,  127,  127,    0,  127,
      115,    0,  114,    0,  116,    0,  116,    0,  115,  133,
      127,  127,  117,  132,  132,    0,  127,  133,  137,    0,
      137,  137,    0,  132,  138,  132,  138,  138,  139,    0,
      139,  139,  140,    0,  140,  140,  141,  132,  141,  141,
        0,  142,  132,  142,  142,  138,    0,  143,    0,  143,
      143,    0,  137,  139,  144,    0,  144,  144,  145,    0,
      145,  145,  142,  146,    0,  146,  146,    0,  140,  143,
      142,    0,    0,  141,  141,  147,    0,  147,  147,  148,

        0,  148,  148,  145,  146,  149,  144,  149,  149,  150,
        0,  150,  150,  151,    0,  151,  151,  152,    0,  152,
      152,  153,    0,  153,  153,  154,    0,  154,  154,  155,
        0,  155,  155,  148,    0,  157,  149,  157,  157,  156,
      151,  156,  156,    0,    0,  158,  152,  158,  158,  159,
        0,  159,  159,  160,    0,  160,  160,    0,    0,    0,
      153,  154,  155,  161,  156,  161,  161,  162,    0,  162,
      162,    0,    0,  157,  163,    0,  163,  163,  160,  164,
        0,  164,  164,  165,  158,  165,  165,  159,    0,  167,
      167,    0,    0,  173,  173,    0,  162,  161,  163,  167,

      164,  167,  170,  173,  170,  173,    0,  170,  170,  175,
      175,    0,    0,  167,  165,    0,    0,  173,  167,    0,
        0,  176,  173,  176,  176,  177,  175,  177,  177,  178,
        0,  178,  178,  179,  175,  179,  179,  180,    0,  180,
      180,  181,    0,  181,  181,  182,    0,  182,  182,  183,
        0,  183,  183,    0,  184,  177,  184,  184,  185,    0,
      185,  185,  186,    0,  186,  186,  187,    0,  187,  187,
      181,  188,    0,  188,  188,  180,  189,    0,  189,  189,
        0,    0,  183,    0,  182,  184,  190,    0,  190,  190,
      191,    0,  191,  191,  192,    0,  192,  192,  186,  193,

        0,  193,  193,  194,  187,  194,  194,  195,    0,  195,
      195,  196,    0,  196,  196,  189,  197,    0,  197,  197,
      198,    0,  198,  198,    0,    0,    0,  191,  194,  199,
      192,  199,  199,  200,    0,  200,  200,  193,    0,  197,
      196,  195,  201,  198,  201,  201,  202,    0,  202,  202,
      208,  208,  203,  199,  203,  203,  204,    0,  204,  204,
      208,  209,  208,  209,  209,  210,  200,  210,  210,  201,
      211,    0,  211,  211,  208,  212,    0,  212,  212,  208,
      213,  204,  213,  213,  214,    0,  214,  214,    0,  215,
      203,  215,  215,  216,    0,  216,  216,  217,    0,  217,

      217,    0,    0,  211,    0,  213,  212,    0,  218,  214,
      218,  218,  219,    0,  219,  219,  220,    0,  220,  220,
        0,  217,  215,  221,    0,  221,  221,  222,    0,  222,
      222,  223,    0,  223,  223,  224,    0,  224,  224,  225,
        0,  225,  225,    0,    0,  219,  218,  221,    0,  226,
        0,  226,  226,  222,  223,  227,    0,  227,  227,  228,
        0,  228,  228,    0,    0,    0,  229,  225,  229,  229,
        0,    0,    0,  224,  226,  230,    0,  230,  230,  232,
        0,  232,  232,  233,    0,  233,  233,  234,    0,  234,
      234,  235,  228,  235,  235,  229,  236,    0,  236,  236,

      237,    0,  237,  237,  238,    0,  238,  238,  239,    0,
      239,  239,  240,    0,  240,  240,    0,  241,  232,  241,
      241,  233,    0,    0,  242,  237,  242,  242,  243,  238,
      243,  243,  244,    0,  244,  244,  245,    0,  245,  245,
      246,    0,  246,  246,  247,    0,  247,  247,  248,    0,
      248,  248,  249,    0,  249,  249,  250,    0,  250,  250,
        0,  251,  245,  251,  251,  246,  252,    0,  252,  252,
        0,    0,    0,  248,  253,  247,  253,  253,  254,    0,
      254,  254,  255,    0,  255,  255,  256,    0,  256,  256,
      257,    0,  257,  257,    0,    0,    0,  251,  253,  258,

        0,  258,  258,  254,  260,  260,  260,  260,  260,  260,
      261,  261,    0,  261,  261,  261,  262,  262,  262,  263,
      263,  263,  263,  263,  263,  264,    0,  264,  264,  264,
      264,  266,  266,  267,  267,  267,  267,  267,  267,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,

      259,  259,  259,  259
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "hw3.l"
#line 2 "hw3.l"
#include <stdio.h>
#include "y.tab.h"
#line 774 "lex.yy.c"
#line 775 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 13 "hw3.l"

#line 994 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1040 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 14 "hw3.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 15 "hw3.l"
{/*comment*/}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 17 "hw3.l"
{return DEFINE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 18 "hw3.l"
{return INCLUDE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 20 "hw3.l"
{return INT;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 21 "hw3.l"
{return CHAR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 23 "hw3.l"
{return VOID;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 24 "hw3.l"
{return FOR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 25 "hw3.l"
{return WHILE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 26 "hw3.l"
{return DO;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 27 "hw3.l"
{return IF;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 28 "hw3.l"
{return SWITCH;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 30 "hw3.l"
{return RETURN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "hw3.l"
{return AUTO;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "hw3.l"
{return BREAK;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "hw3.l"
{return CASE;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "hw3.l"
{return CONST;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "hw3.l"
{return CONTINUE;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "hw3.l"
{return DEFAULT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "hw3.l"
{return DOUBLE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "hw3.l"
{return ENUM;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "hw3.l"
{return EXTERN;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "hw3.l"
{return FLOAT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "hw3.l"
{return GOTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "hw3.l"
{return LONG;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "hw3.l"
{return REGISTER;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "hw3.l"
{return SHORT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "hw3.l"
{return SIGNED;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "hw3.l"
{return SIZEOF;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "hw3.l"
{return STATIC;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "hw3.l"
{return STRUCT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "hw3.l"
{return TYPEDEF;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "hw3.l"
{return UNION;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "hw3.l"
{return UNSIGNED;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "hw3.l"
{return VOLATILE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 55 "hw3.l"
{return HEADER;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "hw3.l"
{return IDENTIFIER;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 60 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 61 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 62 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 42:
/* rule 42 can match eol */
YY_RULE_SETUP
#line 63 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "hw3.l"
{return CONSTANT;}
	YY_BREAK
case 46:
/* rule 46 can match eol */
YY_RULE_SETUP
#line 69 "hw3.l"
{return STRING_LITERAL;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "hw3.l"
{return ELLIPSIS;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "hw3.l"
{return RIGHT_ASSIGN;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "hw3.l"
{return LEFT_ASSIGN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "hw3.l"
{return ADD_ASSIGN;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "hw3.l"
{return SUB_ASSIGN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "hw3.l"
{return MUL_ASSIGN;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "hw3.l"
{return DIV_ASSIGN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 79 "hw3.l"
{return MOD_ASSIGN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 80 "hw3.l"
{return AND_ASSIGN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 81 "hw3.l"
{return XOR_ASSIGN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 82 "hw3.l"
{return OR_ASSIGN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 83 "hw3.l"
{return RIGHT_OP;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 84 "hw3.l"
{return LEFT_OP;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "hw3.l"
{return INC_OP;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "hw3.l"
{return DEC_OP;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 87 "hw3.l"
{return PTR_OP;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 88 "hw3.l"
{return AND_OP;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 89 "hw3.l"
{return OR_OP;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 90 "hw3.l"
{return LE_OP;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 91 "hw3.l"
{return GE_OP;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 92 "hw3.l"
{return EQ_OP;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 93 "hw3.l"
{return NE_OP;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 94 "hw3.l"
{return ';';}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 95 "hw3.l"
{return '{';}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 96 "hw3.l"
{return '}';}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 97 "hw3.l"
{return ',';}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 98 "hw3.l"
{return ':';}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 99 "hw3.l"
{return '=';}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 100 "hw3.l"
{return '(';}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 101 "hw3.l"
{return ')';}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 102 "hw3.l"
{return '[';}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 103 "hw3.l"
{return ']';}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 104 "hw3.l"
{return '.';}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 105 "hw3.l"
{return '&';}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 106 "hw3.l"
{return '!';}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 107 "hw3.l"
{return '~';}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 108 "hw3.l"
{return '-';}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 109 "hw3.l"
{return '+';}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 110 "hw3.l"
{return '*';}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 111 "hw3.l"
{return '/';}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 112 "hw3.l"
{return '%';}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 113 "hw3.l"
{return '<';}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 114 "hw3.l"
{return '>';}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 115 "hw3.l"
{return '^';}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 116 "hw3.l"
{return '|';}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 117 "hw3.l"
{return '?';}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 118 "hw3.l"
{return '#';}
	YY_BREAK
case 94:
/* rule 94 can match eol */
YY_RULE_SETUP
#line 122 "hw3.l"
{/*ignore*/ }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 123 "hw3.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 125 "hw3.l"
ECHO;
	YY_BREAK
#line 1535 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 259);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 125 "hw3.l"



int yywrap(){
	return(1);
} 



